#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"
log_file="$script_dir/installogs.txt" 

while [[ $# -gt 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    printf "\n[${INFO}DRY_RUN${RESET}]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi
  (cd "$(dirname "$1")" && ./"$(basename "$1")")
}

log "$script_dir -- $filter"

scripts=$(find "$script_dir/runs" -maxdepth 1 -mindepth 1 -type f -executable)

for script in $scripts; do
  if echo "$script" | grep -qv "$filter"; then
    log "filtering $script"
    continue
  fi
  execute "$script"
done