#!/usr/bin/env bash

# Only for Linux-- for chipset agnosticism (x86-64, aarch64) this could be replaced by an environment variable-specified chipset: curl "https://awscli.amazonaws.com/awscli-exe-linux-${CHIP_SET}.zip" -o "awscliv2.zip"

# Linux
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

# Macos
curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
sudo installer -pkg AWSCLIV2.pkg -target /