#!/usr/bin/env bash

# Download latest Ghostty .deb
curl -LO https://github.com/ghostty/ghostty/releases/latest/download/ghostty_linux_arm64.deb

# Install with dependencies
sudo apt install ./ghostty_linux_arm64.deb