#!/usr/bin/env bash
sudo apt -y update

if ! command -v git &> /dev/null; then
    sudo apt -y install git
fi

if [ ! -d $HOME/personal ]; then
    mkdir $HOME/personal
fi

git clone https://github.com/aaronjpotter93/dev-env $HOME/personal/dev

# What does this part do??
pushd $HOME/personal/dev
./run
popd