#!/bin/bash
set -e

# Configure timezone non-interactively
export DEBIAN_FRONTEND=noninteractive
export TZ="America/Denver"

# Install dependencies
sudo apt update
sudo apt -y install python3-pip wget gpg git tzdata

# Configure Git
git config --global user.email "aaronjpotter93@gmail.com"
git config --global user.name "aaronjpotter93"

# Create directory and clone repo
mkdir -p "$HOME/personal"
git clone https://github.com/aaronjpotter93/dev "$HOME/personal/dev"

# Navigate to the repo and run the script
pushd "$HOME/personal/dev" > /dev/null
./run
popd > /dev/null