#!/bin/bash
set -e  # Exit immediately if any command fails

# Install dependencies
sudo apt -y install python3-pip
sudo apt-get install wget -y
sudo apt install -y gpg
sudo apt -y install git

# Configure Git
git config --global user.email "aaronjpotter93@gmail.com"
git config --global user.name "aaronjpotter93"

# Create directory and clone repo
mkdir -p "$HOME/personal"
git clone https://github.com/aaronjpotter93/dev "$HOME/personal/dev"

# Navigate to the repo and run the script
pushd "$HOME/personal/dev" > /dev/null
./run
popd > /dev/null