#!/usr/bin/env bash

CHIP_SET=$(uname -m)
OS=$(uname -s)

if ( $OS == "Darwin" ); then
    # MacOS
    curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
    sudo installer -pkg AWSCLIV2.pkg -target /

elif ( $ == "Linux" ); then
    # Linux
    curl "https://awscli.amazonaws.com/awscli-exe-linux-"$(CHIP_SET)".zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
fi
