#!/usr/bin/env bash

sudo apt install nodejs npm
npm config set prefix ~/.local/npm
npm i -g n
n lts

# the prime also has:
# curl -fsSL https://deno.land/install.sh | sh
# curl -fsSL https://bun.sh/install | bash